export const db = {
    Celebrities: [
        {
            id: 1,
            name: 'Marisa Monte',
            twitter: 'https://twitter.com/marisamonte',
            instagram: 'https://www.instagram.com/marisamonte/',
            category: 'Música',
            price: 100,
            categorySecondary: '',
        },
        {
            id: 2,
            name: 'Anitta',
            twitter: 'https://twitter.com/Anitta',
            instagram: 'https://www.instagram.com/anitta/',
            category: 'Música',
            price: 1000,
            categorySecondary: '',
        },
        {
            id: 3,
            name: 'Zeca pagodinho',
            twitter: 'https://twitter.com/zecapagodinho',
            instagram: 'https://www.instagram.com/zecapagodinho/',
            category: 'Música',
            price: 300,
            categorySecondary: '',
        },
        {
            id: 4,
            name: 'Caetano Veloso',
            twitter: 'https://twitter.com/caetanoveloso',
            instagram: 'https://www.instagram.com/caetanoveloso/',
            category: 'Música',
            price: 300,
            categorySecondary: '',
        },
        {
            id: 5,
            name: 'Chico Buarque',
            twitter: '',
            instagram: 'https://www.instagram.com/chicobuarque/',
            category: 'Música',
            price: 500,
            categorySecondary: '',
        },
        {
            id: 6,
            name: 'Ivete Sangalo',
            twitter: 'https://twitter.com/ivetesangalo',
            instagram: 'https://www.instagram.com/ivetesangalo/',
            category: 'Música',
            price: 1000,
            categorySecondary: '',
        },
        {
            id: 7,
            name: 'Gilberto Gil',
            twitter: 'https://twitter.com/gilbertogil',
            instagram: 'https://www.instagram.com/gilbertogil/',
            category: 'Música',
            price: 100,
            categorySecondary: '',
        },
        {
            id: 8,
            name: 'Milton Nascimento',
            twitter: 'https://twitter.com/MiltonBituca',
            instagram: 'https://www.instagram.com/miltonbitucanascimento/',
            category: 'Música',
            price: 75,
            categorySecondary: '',
        },
        {
            id: 9,
            name: 'Djavan',
            twitter: 'https://twitter.com/djavanoficial',
            instagram: 'https://www.instagram.com/djavanoficial/',
            category: 'Música',
            price: 75,
            categorySecondary: '',
        },
        {
            id: 10,
            name: 'Gustavo Lima',
            twitter: 'https://twitter.com/gusttavo_lima',
            instagram: 'https://www.instagram.com/gusttavolima/',
            category: 'Música',
            price: 500,
            categorySecondary: '',
        },
        {
            id: 11,
            name: 'Pabllo Vittar',
            twitter: 'https://twitter.com/pabllovittar',
            instagram: 'https://www.instagram.com/pabllovittar/',
            category: 'Música',
            price: 200,
            categorySecondary: '',
        },
        {
            id: 12,
            name: 'Marília Mendonça',
            twitter: 'https://twitter.com/MariliaMReal',
            instagram: 'https://www.instagram.com/mariliamendoncacantora/',
            category: 'Música',
            price: 300,
            categorySecondary: '',
        },
        {
            id: 13,
            name: 'Wesley Safadão',
            twitter: 'https://twitter.com/WesleySafadao',
            instagram: 'https://www.instagram.com/wesleysafadao/',
            category: 'Música',
            price: 500,
            categorySecondary: '',
        },
        {
            id: 14,
            name: 'Luan Santana',
            twitter: 'https://twitter.com/luansantana',
            instagram: 'https://www.instagram.com/luansantana/',
            category: 'Música',
            price: 500,
            categorySecondary: '',
        },
        {
            id: 15,
            name: 'Kevinho',
            twitter: 'https://twitter.com/kevinho',
            instagram: 'https://www.instagram.com/kevinho/',
            category: 'Música',
            price: 400,
            categorySecondary: '',
        },
        {
            id: 16,
            name: 'Rita Lee',
            twitter: '',
            instagram: 'https://www.instagram.com/ritalee_oficial/',
            category: 'Música',
            price: 125,
            categorySecondary: '',
        },
        {
            id: 17,
            name: 'Ney Matogrosso',
            twitter: '',
            instagram: 'https://www.instagram.com/neymatogrosso/',
            category: 'Música',
            price: 75,
            categorySecondary: '',
        },
        {
            id: 18,
            name: 'Jorge Ben Jor',
            twitter: 'https://twitter.com/jorgebenjor',
            instagram: 'https://www.instagram.com/jorgebenjoroficial/',
            category: 'Música',
            price: 60,
            categorySecondary: '',
        },
        {
            id: 19,
            name: 'Sandy',
            twitter: 'https://twitter.com/SandyLeah',
            instagram: 'https://www.instagram.com/sandyoficial/',
            category: 'Música',
            price: 100,
            categorySecondary: '',
        },
        {
            id: 20,
            name: 'Xuxa',
            twitter: 'https://twitter.com/xuxameneghel',
            instagram: 'https://www.instagram.com/xuxameneghel/',
            category: 'Música',
            price: 500,
            categorySecondary: 'Televisão',
        },
        {
            id: 21,
            name: 'Dudu',
            twitter: '',
            instagram: 'https://www.instagram.com/7_dudu/',
            category: 'Futebol',
            price: 100,
            categorySecondary: '',
        },
        {
            id: 22,
            name: 'Gabigol',
            twitter: 'https://twitter.com/gabigol',
            instagram: 'https://www.instagram.com/gabigol/',
            category: 'Futebol',
            price: 500,
            categorySecondary: '',
        },
        {
            id: 23,
            name: 'Ronaldinho Gaúcho',
            twitter: 'https://twitter.com/10Ronaldinho',
            instagram: 'https://www.instagram.com/ronaldinho/',
            category: 'Futebol',
            price: 1000,
            categorySecondary: '',
        },
        {
            id: 24,
            name: 'Neymar',
            twitter: 'https://twitter.com/neymarjr',
            instagram: 'https://www.instagram.com/neymarjr/',
            category: 'Futebol',
            price: 3000,
            categorySecondary: '',
        },
        {
            id: 25,
            name: 'Daniel Alves',
            twitter: 'https://twitter.com/DaniAlvesD2',
            instagram: 'https://www.instagram.com/danialves/',
            category: 'Futebol',
            price: 400,
            categorySecondary: '',
        },
        {
            id: 26,
            name: 'Alisson  Becker',
            twitter: 'https://twitter.com/Alissonbecker',
            instagram: 'https://www.instagram.com/alissonbecker/',
            category: 'Futebol',
            price: 700,
            categorySecondary: '',
        },
        {
            id: 27,
            name: 'Philippe Coutinho',
            twitter: 'https://twitter.com/Phil_Coutinho',
            instagram: 'https://www.instagram.com/phil.coutinho/',
            category: 'Futebol',
            price: 400,
            categorySecondary: '',
        },
        {
            id: 28,
            name: 'Rogério Ceni',
            twitter: 'https://twitter.com/rogerioceni',
            instagram: 'https://www.instagram.com/rogerio.ceni.01/',
            category: 'Futebol',
            price: 100,
            categorySecondary: '',
        },
        {
            id: 29,
            name: 'Everton Ribeiro',
            twitter: 'https://twitter.com/evertonri',
            instagram: 'https://www.instagram.com/evertonri/',
            category: 'Futebol',
            price: 200,
            categorySecondary: '',
        },
        {
            id: 30,
            name: 'Alexandre Pato',
            twitter: 'https://twitter.com/Pato',
            instagram: 'https://www.instagram.com/pato/',
            category: 'Futebol',
            price: 75,
            categorySecondary: '',
        },
        {
            id: 31,
            name: 'Pelé',
            twitter: 'https://twitter.com/Pele',
            instagram: 'https://www.instagram.com/pele/',
            category: 'Futebol',
            price: 1000,
            categorySecondary: '',
        },
        {
            id: 32,
            name: 'Ronaldo',
            twitter: 'https://twitter.com/Ronaldo',
            instagram: 'https://www.instagram.com/ronaldo/',
            category: 'Futebol',
            price: 400,
            categorySecondary: '',
        },
        {
            id: 33,
            name: 'Zico',
            twitter: '',
            instagram: 'https://www.instagram.com/zico/',
            category: 'Futebol',
            price: 125,
            categorySecondary: '',
        },
        {
            id: 34,
            name: 'Firmino',
            twitter: 'https://twitter.com/Nick_F_28',
            instagram: 'https://www.instagram.com/roberto_firmino/',
            category: 'Futebol',
            price: 350,
            categorySecondary: '',
        },
        {
            id: 35,
            name: 'Fabinho',
            twitter: 'https://twitter.com/_fabinhotavares',
            instagram: 'https://www.instagram.com/fabinho/',
            category: 'Futebol',
            price: 150,
            categorySecondary: '',
        },
        {
            id: 36,
            name: 'David Luiz',
            twitter: 'https://twitter.com/DavidLuiz_4',
            instagram: 'https://www.instagram.com/davidluiz_4/',
            category: 'Futebol',
            price: 350,
            categorySecondary: '',
        },
        {
            id: 37,
            name: 'Kaká',
            twitter: 'https://twitter.com/KAKA',
            instagram: 'https://www.instagram.com/kaka/',
            category: 'Futebol',
            price: 250,
            categorySecondary: '',
        },
        {
            id: 38,
            name: 'Fred',
            twitter: 'https://twitter.com/fredgol9',
            instagram: 'https://www.instagram.com/fredguedes9/',
            category: 'Futebol',
            price: 75,
            categorySecondary: '',
        },
        {
            id: 39,
            name: 'Taffarel',
            twitter: '',
            instagram: 'https://www.instagram.com/taffareloriginal/',
            category: 'Futebol',
            price: 50,
            categorySecondary: '',
        },
        {
            id: 40,
            name: 'Ana Maria Braga',
            twitter: 'https://twitter.com/ANAMARIABRAGA',
            instagram: 'https://www.instagram.com/anamaria16/',
            category: 'Televisão',
            price: 350,
            categorySecondary: '',
        },
        {
            id: 41,
            name: 'Faustão',
            twitter: '',
            instagram: 'https://www.instagram.com/faustosilvaofcial/',
            category: 'Televisão',
            price: 1000,
            categorySecondary: '',
        },
        {
            id: 42,
            name: 'Luciano Huck',
            twitter: 'https://twitter.com/lucianohuck',
            instagram: 'https://www.instagram.com/lucianohuck/',
            category: 'Televisão',
            price: 750,
            categorySecondary: '',
        },
        {
            id: 43,
            name: 'William Bonner',
            twitter: 'https://twitter.com/realwbonner',
            instagram: 'https://www.instagram.com/realwbonner/',
            category: 'Televisão',
            price: 500,
            categorySecondary: '',
        },
        {
            id: 44,
            name: 'Silvio Santos',
            twitter: '',
            instagram: 'https://www.instagram.com/pgmsilviosantos/',
            category: 'Televisão',
            price: 1000,
            categorySecondary: '',
        },
        {
            id: 45,
            name: 'Jô Soares',
            twitter: '',
            instagram: '',
            category: 'Televisão',
            price: 150,
            categorySecondary: '',
        },
        {
            id: 46,
            name: 'Eliana',
            twitter: 'https://twitter.com/Eliana',
            instagram: 'https://www.instagram.com/eliana/',
            category: 'Televisão',
            price: 450,
            categorySecondary: '',
        },
        {
            id: 47,
            name: 'Galvão Bueno',
            twitter: 'https://twitter.com/galvaobueno',
            instagram: 'https://www.instagram.com/galvaobueno/',
            category: 'Televisão',
            price: 300,
            categorySecondary: '',
        },
        {
            id: 48,
            name: 'Ana Hickmann',
            twitter: 'https://twitter.com/ahickmann',
            instagram: 'https://www.instagram.com/ahickmann/',
            category: 'Televisão',
            price: 250,
            categorySecondary: '',
        },
        {
            id: 49,
            name: 'Sabrina Sato',
            twitter: 'https://twitter.com/SabrinaSato',
            instagram: 'https://www.instagram.com/sabrinasato/',
            category: 'Televisão',
            price: 300,
            categorySecondary: '',
        },
        {
            id: 50,
            name: 'Rodrigo Faro',
            twitter: 'https://twitter.com/RodrigoFaro',
            instagram: 'https://www.instagram.com/rodrigofaro/',
            category: 'Televisão',
            price: 250,
            categorySecondary: '',
        },
        {
            id: 51,
            name: 'Fátima Bernardes',
            twitter: 'https://twitter.com/fbbreal',
            instagram: 'https://www.instagram.com/fatimabernardes/',
            category: 'Televisão',
            price: 500,
            categorySecondary: '',
        },
        {
            id: 52,
            name: 'Ratinho',
            twitter: 'https://twitter.com/ratinhodosbt',
            instagram: 'https://www.instagram.com/oratinho/',
            category: 'Televisão',
            price: 350,
            categorySecondary: '',
        },
        {
            id: 53,
            name: 'Tiago Leifert',
            twitter: '',
            instagram: 'https://www.instagram.com/tiagoleifert/',
            category: 'Televisão',
            price: 250,
            categorySecondary: '',
        },
        {
            id: 54,
            name: 'Luciana Gimenez',
            twitter: 'https://twitter.com/LucianaGimenez',
            instagram: 'https://www.instagram.com/lucianagimenez/',
            category: 'Televisão',
            price: 350,
            categorySecondary: '',
        },
        {
            id: 55,
            name: 'Sandra Annenberg',
            twitter: 'https://twitter.com/sandraannenberg',
            instagram: 'https://www.instagram.com/sandra.annenberg.real/',
            category: 'Televisão',
            price: 275,
            categorySecondary: '',
        },
        {
            id: 56,
            name: 'Danilo Gentili',
            twitter: 'https://twitter.com/DaniloGentili',
            instagram: 'https://www.instagram.com/danilogentili/',
            category: 'Televisão',
            price: 400,
            categorySecondary: '',
        },
        {
            id: 57,
            name: 'Pedro Bial',
            twitter: 'https://twitter.com/PBiaL',
            instagram: 'https://www.instagram.com/pedrobial/',
            category: 'Televisão',
            price: 350,
            categorySecondary: '',
        },
        {
            id: 58,
            name: 'Celso Portiolli',
            twitter: 'https://twitter.com/celsoportiolli',
            instagram: 'https://www.instagram.com/celsoportiolli/',
            category: 'Televisão',
            price: 250,
            categorySecondary: '',
        },
        {
            id: 59,
            name: 'Marcos Mion',
            twitter: 'https://twitter.com/marcosmion',
            instagram: 'https://www.instagram.com/marcosmion/',
            category: 'Televisão',
            price: 300,
            categorySecondary: '',
        },
    ],
};
